version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: 'true'
      ROCKET_BASE_PATH: '/vault'
    volumes:
      - ./vaultwarden/data:/data
    expose:
      - 80
    networks:
      - nginx_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/vaultwarden.conf:/data/nginx/proxy_host/vaultwarden/location.conf:ro
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
