version: '3.8'

services:
  # Vaultwarden service, served at /vault with sub-path support
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      # Must include sub-path and trailing slash for proper link generation
      DOMAIN: "http://192.168.1.146/"
    ports:
      - 80:80
    networks:
      - web

networks:
  web:
    driver: bridge
