version: '3.8'

services:
  # Reverse proxy using Traefik
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=your-email@example.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  # Example App: whoami (for testing path routing)
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=whoami-strip"
      - "traefik.http.middlewares.whoami-strip.stripprefix.prefixes=/whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - web

  # Vaultwarden service, served at /vault
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      # Include full path with trailing slash
      DOMAIN: "http://192.168.1.50/vault/"
    labels:
      - "traefik.enable=true"
      # 1) Exact /vault → redirect to /vault/
      - "traefik.http.routers.vaultwarden-root.rule=Path(`/vault`)"
      - "traefik.http.routers.vaultwarden-root.entrypoints=web"
      - "traefik.http.routers.vaultwarden-root.middlewares=vw-add-slash"
      - "traefik.http.middlewares.vw-add-slash.redirectregex.regex=^/vault$$"
      - "traefik.http.middlewares.vw-add-slash.redirectregex.replacement=/vault/"
      # 2) Everything under /vault/ → strip prefix and proxy
      - "traefik.http.routers.vaultwarden.rule=PathPrefix(`/vault/`)"
      - "traefik.http.routers.vaultwarden.entrypoints=web"
      - "traefik.http.routers.vaultwarden.middlewares=vw-strip-prefix"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.middlewares.vw-strip-prefix.stripprefix.prefixes=/vault/"
    networks:
      - web

networks:
  web:
    driver: bridge