version: "3.8"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      # Expose Vaultwarden's web UI on host port 80
      - "80:80"
    volumes:
      # Persist data (DB, attachments, config)
      - ./vw-data:/data
    environment:
      # Prevent public self-signups by default
      SIGNUPS_ALLOWED: "false"
      # Enable websockets for live updates
      WEBSOCKET_ENABLED: "true"
      # (Optional) set an admin token for /admin endpoint
      # ADMIN_TOKEN: "your-long-random-token"
      # You can add LOG_LEVEL, ROCKET_ENV, etc. as needed