version: "3.8"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      # Tell Vaultwarden what its public URL is (must be https for attachments)
      DOMAIN: "https://${DOMAIN}"
    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"   # HTTP/3
    volumes:
      - ./caddy:/usr/bin/caddy       # if you’ve built a custom Caddy binary
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    env_file:
      - .env
    environment:
      DOMAIN: "${DOMAIN}"  # Your domain.
      EMAIL: "admin@example.com"                 # The email address to use for ACME registration.
      DUCKDNS_TOKEN: "${DUCKDNS_TOKEN}"                   # Your Duck DNS token.
      LOG_FILE: "/data/access.log"